In [1]:
import sqlite3
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

print("All four packages imported successfully.")

All four packages imported successfully.

In [2]:
conn = sqlite3.connect('week_09_data.db')

cursor = conn.cursor()

In [3]:
pd.read_csv('sales.csv').to_sql('sales',conn, if_exists='replace',index=False)

20

In [4]:
#Student_Practice_01

pd.read_sql_query('''
SELECT sale_date, product, price FROM sales
''',conn)

    sale_date     product   price
0    9/1/2026      Laptop  999.99
1    9/1/2026       Mouse   24.99
2    9/2/2026     Monitor  199.99
3    9/2/2026    Keyboard   49.99
4    9/3/2026      Laptop  999.99
5    9/3/2026  Headphones   79.99
6    9/4/2026       Mouse   24.99
7    9/4/2026     Monitor  199.99
8    9/5/2026      Laptop  999.99
9    9/5/2026    Keyboard   49.99
10   9/6/2026  Headphones   79.99
11   9/6/2026      Tablet  449.99
12   9/7/2026       Mouse   24.99
13   9/7/2026      Tablet  449.99
14   9/8/2026     Monitor  199.99
15   9/8/2026      Laptop  999.99
16   9/9/2026    Keyboard   49.99
17   9/9/2026  Headphones   79.99
18  9/10/2026      Tablet  449.99
19  9/10/2026       Mouse   24.99

In [5]:
pd.read_csv('hr_employees.csv').to_sql('employees',conn,if_exists='replace',index=False)

30

In [6]:
#Student_Practice_02

pd.read_sql_query('''
SELECT name, department, salary
FROM employees
WHERE city = 'Chicago' AND years_experience > 10
''',conn)

   name  department  salary
0  Lily  Operations   56000

In [7]:
pd.read_csv('realestate_listings.csv').to_sql('listings',conn,if_exists='replace',index=False)

25

In [8]:
#Student_Practice_03

pd.read_sql_query('''
SELECT *
FROM listings
ORDER BY sqft DESC
LIMIT 3
''',conn)

,listing_id,neighborhood,property_type,bedrooms,sqft,list_price,days_on_market
0,204,Riverside,Condo,5,3736,979000,71
1,206,Maple Grove,Condo,5,3693,1001000,52
2,209,Maple Grove,House,1,3499,661000,116

In [9]:
pd.read_csv('marketing_campaigns.csv').to_sql('campaigns',conn,if_exists='replace',index=False)

40

In [10]:
#Student_Practice_04

pd.read_sql_query('''
SELECT campaign, SUM(impressions) AS total_impressions
FROM campaigns
GROUP BY campaign
''',conn)

         campaign  total_impressions
0  Back to School             352622
1   Holiday Promo             468724
2     Spring Sale             392558
3   Summer Launch             399890

In [11]:
pd.read_csv('restaurant_orders.csv').to_sql('orders',conn,if_exists='replace',index=False)

50

In [12]:
#Student_Practice_05

pd.read_sql_query('''
SELECT order_date, SUM(order_total) AS total_sales
FROM orders
GROUP BY order_date
HAVING SUM(order_total) > 400
''',conn)

   order_date  total_sales
0  2026-10-02       492.14
1  2026-10-05       850.10
2  2026-10-07       415.94
3  2026-10-12       633.98

In [13]:
pd.read_csv('clinic_visits.csv').to_sql('visits',conn,if_exists='replace',index=False)

35

In [14]:
#Student_Practice_06

pd.read_sql_query('''
SELECT doctor, ROUND(AVG(patient_age),0) AS avg_age, MAX(wait_minutes) AS longest_wait
FROM visits
GROUP BY doctor
''',conn)

      doctor  avg_age  longest_wait
0  Dr. Adams     47.0            75
1   Dr. Chen     58.0            50
2  Dr. Gomez     34.0            75
3  Dr. Patel     45.0            59
4  Dr. Scott     45.0            63

In [15]:
pd.read_csv('bank_customers.csv').to_sql('customers',conn,if_exists='replace',index=False)
pd.read_csv('bank_transactions.csv').to_sql('transactions',conn,if_exists='replace',index=False)

45

In [16]:
#Student_Practice_07

pd.read_sql_query('''
SELECT c.branch, SUM(t.amount) AS total_amount
FROM transactions AS t
JOIN customers AS c ON t.customer_id = c.customer_id
GROUP BY c.branch
''',conn)

      branch  total_amount
0    Airport      15177.98
1    Main St       3581.19
2  Northgate      19546.49
3   Westside      13996.30

In [17]:
conn.close()